name: Mirror to Codeberg

on:
  push:
    branches:
      - v4
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        run: |
          git remote add codeberg https://${{ secrets.CODEBERG_USERNAME }}:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/Gioppo/notte-inquieta-sfera-di-chrono-quartz.git
          git push codeberg v4
          git push codeberg --tags
